gitGraph
    commit id:"3e8a5ca" tag:"Initial commit"
    commit id:"9c3d150" tag:"Initial PFAS package"
    commit id:"698ee3a" tag:"Sync merge"
    branch improvements-v1
    checkout improvements-v1
    commit id:"5c1bdfa" tag:"Dual orientation + reorg"
    checkout main
    merge improvements-v1 tag:"67b4c17"
    branch V2
    checkout V2
    commit id:"38f3d3e" tag:"Modular architecture"
    checkout main
    merge V2 tag:"8787cbd"
